version: '3'

services:
  postgres:
    restart: always
    image: postgres:16.0-alpine
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql

