server:
  port: ${PORT:8080}
postgres:
  host: ${POSTGRES_HOST:localhost}
  port: ${POSTGRES_PORT:5432}
  db-name: ${POSTGRES_DN_NAME:postgres}
  table-prefix: ${POSTGRES_TABLE_PREFIX:wisdom.}
  username: ${POSTGRES_USERNAME:postgres}
  password: ${POSTGRES_PASSWORD:postgres}
  ssl-mode: ${POSTGRES_SSL_MODE:false}
